kind: Service
apiVersion: v1
metadata:
  name: chat-app
  labels:
    app: chat
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31252
  selector:
    app: chat
  type: LoadBalancer